version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: docker-develop.dockerfile
    container_name: fastapi-develop
    environment: 
      - POSTGRES_SERVER=database-pg
    env_file: ../../develop.env
    ports:
      - 80:80
    depends_on:
      - database

  database:
    image: "postgres:latest"
    container_name: database-pg
    restart: always
    ports:
      - 5432:5432
    env_file: ../../develop.env
    volumes:
      - pgsql_volume:/var/lib/postgresql/data

  
volumes:
  pgsql_volume: